const GET_CONFIGURATION_API = 'get_user_configuration';
const SAVE_CONFIGURATION_API = 'save_user_configuration';

export const typesApi = {
  GET_CONFIGURATION_API,
  SAVE_CONFIGURATION_API
};

const GET_CONFIGURATION_ACTION = 'COMMON/GET_CONFIGURATION_ACTION';
const SAVE_CONFIGURATION_ACTION = 'COMMON/SAVE_CONFIGURATION_ACTION';

export const typesAction = {
  GET_CONFIGURATION_ACTION,
  SAVE_CONFIGURATION_ACTION
};
