@current_pass = qweasd
@new_pass = qweasd

POST /change_password HTTP/1.1
Host: {{host}}
Authorization: Bearer {{access_token}}
Content-Type: multipart/form-data; boundary=--------------------------boundary

----------------------------boundary
Content-Disposition: form-data; name="current_pass"

{{current_pass}}
----------------------------boundary
Content-Disposition: form-data; name="new_pass"

{{new_pass}}
----------------------------boundary--
