@email = admin@cisbox.com
@password = qweasd
@reset_password_token = 253fdabc-7a9c-4c17-9f14-440b9574f4a7

POST /users/reset_password HTTP/1.1
Host: {{host}}
Content-Type: multipart/form-data; boundary=--------------------------boundary

----------------------------boundary
Content-Disposition: form-data; name="email"

{{email}}
----------------------------boundary
Content-Disposition: form-data; name="password"

{{password}}
----------------------------boundary
Content-Disposition: form-data; name="reset_password_token"

{{reset_password_token}}
----------------------------boundary--
