const GET_ITEMS_TREND_API = 'dashboard/items_trend';
const GET_INVOICE_OVERVIEW_API = 'dashboard/invoice_overview';
const GET_INVOICE_ITEMS_OVERVIEW_API = 'dashboard/invoices_items_overview';

export const typesApi = {
  GET_ITEMS_TREND_API,
  GET_INVOICE_OVERVIEW_API,
  GET_INVOICE_ITEMS_OVERVIEW_API
};

const GET_ITEMS_TREND_ACTION = 'DASHBOARD/GET_ITEMS_TREND_ACTION';
const GET_INVOICE_OVERVIEW_ACTION = 'DASHBOARD/GET_INVOICE_OVERVIEW_ACTION';
const GET_INVOICE_ITEMS_OVERVIEW_ACTION = 'DASHBOARD/GET_INVOICE_ITEMS_OVERVIEW_ACTION';

export const typesAction = {
  GET_ITEMS_TREND_ACTION,
  GET_INVOICE_OVERVIEW_ACTION,
  GET_INVOICE_ITEMS_OVERVIEW_ACTION
};
