const GET_ALLOCATION_ARCHIVES_API = 'invoice_archives';
const GET_ALLOCATION_ARCHIVES_DETAIL_API = 'invoice_detail_archives';

export const typesApi = {
  GET_ALLOCATION_ARCHIVES_API,
  GET_ALLOCATION_ARCHIVES_DETAIL_API
};

const GET_ALLOCATION_ARCHIVES_ACTION = 'ALLOCATION_ARCHIVES/GET_ALLOCATION_ARCHIVES_ACTION';
const GET_ALLOCATION_ARCHIVES_DETAIL_ACTION = 'ALLOCATION_ARCHIVES/GET_ALLOCATION_ARCHIVES_DETAIL_ACTION';

export const typesAction = {
  GET_ALLOCATION_ARCHIVES_ACTION,
  GET_ALLOCATION_ARCHIVES_DETAIL_ACTION
};
