const GET_GROUPS_API = 'companies_by_user_id';
const GET_GROUPS_ALL_API = 'companies_get_all_by_user_id';
const GET_GROUPS_DETAIL_API = 'account_company_by_public_id';
const GET_GROUPS_ACCOUNTS_BY_COMPANY_NO_API = 'account_company_by_company_no';
const SAVE_ACCOUNTS_CHECKED_API = 'account_checked';
const SAVE_ACCOUNTS_PLAN_MAPPING_API = 'account_save_plan_mapping';

export const typesApi = {
  GET_GROUPS_API,
  GET_GROUPS_ALL_API,
  GET_GROUPS_DETAIL_API,
  GET_GROUPS_ACCOUNTS_BY_COMPANY_NO_API,
  SAVE_ACCOUNTS_CHECKED_API,
  SAVE_ACCOUNTS_PLAN_MAPPING_API
};

const GET_GROUPS_ACTION = 'GROUP_ACCOUNTS/GET_GROUPS_ACTION';
const GET_GROUPS_ALL_ACTION = 'GROUP_ACCOUNTS/GET_GROUPS_ALL_ACTION';
const GET_GROUPS_DETAIL_ACTION = 'GROUP_ACCOUNTS/GET_GROUP_ACCOUNTS_COMPANY_ACTION';
const GET_GROUPS_ACCOUNTS_BY_COMPANY_NO_ACTION = 'GROUP_ACCOUNTS/GET_GROUPS_ACCOUNTS_BY_COMPANY_NO_ACTION';
const SAVE_ACCOUNTS_CHECKED_ACTION = 'GROUP_ACCOUNTS/SAVE_ACCOUNTS_CHECKED_ACTION';
const SAVE_ACCOUNTS_PLAN_MAPPING_ACTION = 'GROUP_ACCOUNTS/SAVE_ACCOUNTS_PLAN_MAPPING_ACTION';

export const typesAction = {
  GET_GROUPS_ACTION,
  GET_GROUPS_ALL_ACTION,
  GET_GROUPS_DETAIL_ACTION,
  GET_GROUPS_ACCOUNTS_BY_COMPANY_NO_ACTION,
  SAVE_ACCOUNTS_CHECKED_ACTION,
  SAVE_ACCOUNTS_PLAN_MAPPING_ACTION
};
