const GET_ALLOCATION_ITEMS_API = 'invoice_overview';
const GET_ALLOCATION_ITEMS_DETAIL_API = 'invoice_detail';
const SAVE_ALLOCATION_ITEMS_DETAIL_API = 'invoice_detail_saving';

const GET_ALLOCATION_INVOICE_IMAGES_API = 'invoice/get_images';

export const typesApi = {
  GET_ALLOCATION_ITEMS_API,
  GET_ALLOCATION_ITEMS_DETAIL_API,
  SAVE_ALLOCATION_ITEMS_DETAIL_API,
  GET_ALLOCATION_INVOICE_IMAGES_API
};

const GET_ALLOCATION_ITEMS_ACTION = 'ALLOCATION_ITEMS/GET_ALLOCATION_ITEMS_ACTION';
const GET_ALLOCATION_ITEMS_DETAIL_ACTION = 'ALLOCATION_ITEMS/GET_ALLOCATION_ITEMS_DETAIL_ACTION';
const SAVE_ALLOCATION_ITEMS_DETAIL_ACTION = 'ALLOCATION_ITEMS/SAVE_ALLOCATION_ITEMS_DETAIL_ACTION';

const GET_ALLOCATION_INVOICE_IMAGES_ACTION = 'ALLOCATION_ITEMS/GET_ALLOCATION_INVOICE_IMAGES_API';

export const typesAction = {
  GET_ALLOCATION_ITEMS_ACTION,
  GET_ALLOCATION_ITEMS_DETAIL_ACTION,
  SAVE_ALLOCATION_ITEMS_DETAIL_ACTION,
  GET_ALLOCATION_INVOICE_IMAGES_ACTION
};
