const GET_ALLOCATION_ITEMS_API = 'invoice_overview';
const GET_ALLOCATION_ITEMS_DETAIL_API = 'invoice_detail';
const GET_ALLOCATION_INVOICE_IMAGES_API = 'invoice/get_images';

const SAVE_ALLOCATION_ITEMS_DETAIL_API = 'invoice_detail_saving';

const GET_CLARIFICATION_GET_COMMENTS_API = 'clarification/get_comment_clarification';
const GET_CLARIFICATION_GET_CATEGORIES_API = 'clarification/get_category';

const REPLY_CLARIFICATION_API = 'clarification/reply_clarification';
const COMMENT_CLARIFICATION_API = 'clarification/comment_clarification';

export const typesApi = {
  GET_ALLOCATION_ITEMS_API,
  GET_ALLOCATION_ITEMS_DETAIL_API,
  GET_ALLOCATION_INVOICE_IMAGES_API,

  SAVE_ALLOCATION_ITEMS_DETAIL_API,

  GET_CLARIFICATION_GET_COMMENTS_API,
  GET_CLARIFICATION_GET_CATEGORIES_API,

  REPLY_CLARIFICATION_API,
  COMMENT_CLARIFICATION_API
};

const GET_ALLOCATION_ITEMS_ACTION = 'ALLOCATION_ITEMS/GET_ALLOCATION_ITEMS_ACTION';
const GET_ALLOCATION_ITEMS_DETAIL_ACTION = 'ALLOCATION_ITEMS/GET_ALLOCATION_ITEMS_DETAIL_ACTION';
const SAVE_ALLOCATION_ITEMS_DETAIL_ACTION = 'ALLOCATION_ITEMS/SAVE_ALLOCATION_ITEMS_DETAIL_ACTION';
const GET_ALLOCATION_INVOICE_IMAGES_ACTION = 'ALLOCATION_ITEMS/GET_ALLOCATION_INVOICE_IMAGES_API';
const GET_CLARIFICATION_GET_COMMENTS_ACTION = 'ALLOCATION_ITEMS/GET_CLARIFICATION_GET_COMMENTS_ACTION';
const GET_CLARIFICATION_GET_CATEGORIES_ACTION = 'ALLOCATION_ITEMS/GET_CLARIFICATION_GET_CATEGORIES_ACTION';
const REPLY_CLARIFICATION_ACTION = 'ALLOCATION_ITEMS/REPLY_CLARIFICATION_ACTION';
const COMMENT_CLARIFICATION_ACTION = 'ALLOCATION_ITEMS/COMMENT_CLARIFICATION_ACTION';

export const typesAction = {
  GET_ALLOCATION_ITEMS_ACTION,
  GET_ALLOCATION_ITEMS_DETAIL_ACTION,
  GET_ALLOCATION_INVOICE_IMAGES_ACTION,

  SAVE_ALLOCATION_ITEMS_DETAIL_ACTION,

  GET_CLARIFICATION_GET_COMMENTS_ACTION,
  GET_CLARIFICATION_GET_CATEGORIES_ACTION,

  REPLY_CLARIFICATION_ACTION,
  COMMENT_CLARIFICATION_ACTION
};
