POST /invoice_detail_saving HTTP/1.1
Host: {{host}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "data": [
    {
      "id": 11,
      "account_id": 10,
      "account_no": "277",
      "system_account_id": 0,
      "system_account_no": 0,
      "company_no": 0
    }
  ]
}
