POST /invoice_detail_saving HTTP/1.1
Host: {{host}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "status": "allocation1",
  "company_no": 0,
  "data": [
    {
      "id": 11,
      "invoice_id": 11,
      "invoice_position_id": 5312,
      "account_id": 10,
      "account_no": "277",
      "system_account_id": 0,
      "system_account_no": 0,
      "clarification_detail": [{
        "clarification_id": 1,
        "reply_comment": "Test",
        "current_status": "clarification1",
        "next_status": "exported",
        "invoice_account_reference_ids": [
          123,
          124
        ]
      }]
    }
  ]
}
