@company_no = 171
@from_date = 2024-01-01
@to_date = 2024-06-30
@keyword = 
@sort = 
@sort_direction = 1
@page_current = 1
@page_size = 50

GET /invoice_archives?company_no={{company_no}}&from_date={{from_date}}&to_date={{to_date}}&keyword={{keyword}}&sort={{sort}}&sort_direction={{sort_direction}}&page_current={{page_current}}&page_size={{page_size}} HTTP/1.1
Host: {{host}}
Authorization: Bearer {{access_token}}
