const GET_ITEMS_HISTORY_API = 'items_history';
const GET_ITEMS_BY_GROUP_AND_ACCOUNT_API = 'items_by_group_and_account';

export const typesApi = {
  GET_ITEMS_HISTORY_API,
  GET_ITEMS_BY_GROUP_AND_ACCOUNT_API
};

const GET_ITEMS_HISTORY_ACTION = 'ITEMS/GET_ITEMS_HISTORY_ACTION';
const GET_ITEMS_BY_GROUP_AND_ACCOUNT_ACTION = 'ITEMS/GET_ITEMS_BY_GROUP_AND_ACCOUNT_ACTION';

export const typesAction = {
  GET_ITEMS_HISTORY_ACTION,
  GET_ITEMS_BY_GROUP_AND_ACCOUNT_ACTION
};
