const GET_SYSTEM_ACCOUNTS_API = 'account_system';
const GET_SYSTEM_ACCOUNTS_DETAIL_API = 'account_system_details';
const GET_SYSTEM_ACCOUNTS_BY_COMPANY_NO_API = 'account_system_by_company_no';
const GET_SYSTEM_COMPANY_ACCOUNTS_BY_COMPANY_NO_API = 'account_system_company_by_company_no';
const CREATE_SYSTEM_ACCOUNTS_API = 'system_account/create';
const DELETE_SYSTEM_ACCOUNTS_API = 'system_account/delete';

export const typesApi = {
  GET_SYSTEM_ACCOUNTS_API,
  GET_SYSTEM_ACCOUNTS_DETAIL_API,
  GET_SYSTEM_ACCOUNTS_BY_COMPANY_NO_API,
  GET_SYSTEM_COMPANY_ACCOUNTS_BY_COMPANY_NO_API,
  CREATE_SYSTEM_ACCOUNTS_API,
  DELETE_SYSTEM_ACCOUNTS_API
};

const GET_SYSTEM_ACCOUNTS_ACTION = 'SYSTEM_ACCOUNTS/GET_SYSTEM_ACCOUNTS_ACTION';
const GET_SYSTEM_ACCOUNTS_DETAIL_ACTION = 'SYSTEM_ACCOUNTS/GET_SYSTEM_ACCOUNTS_DETAILS_ACTION';
const GET_SYSTEM_ACCOUNTS_BY_COMPANY_NO_ACTION = 'SYSTEM_ACCOUNTS/GET_SYSTEM_ACCOUNTS_BY_COMPANY_NO_ACTION';
const GET_SYSTEM_COMPANY_ACCOUNTS_BY_COMPANY_NO_ACTION =
  'SYSTEM_ACCOUNTS/GET_SYSTEM_COMPANY_ACCOUNTS_BY_COMPANY_NO_ACTION';
const CREATE_SYSTEM_ACCOUNTS_ACTION = 'SYSTEM_ACCOUNTS/CREATE_SYSTEM_ACCOUNTS_ACTION';
const DELETE_SYSTEM_ACCOUNTS_ACTION = 'SYSTEM_ACCOUNTS/DELETE_SYSTEM_ACCOUNTS_ACTION';

export const typesAction = {
  GET_SYSTEM_ACCOUNTS_ACTION,
  GET_SYSTEM_ACCOUNTS_DETAIL_ACTION,
  GET_SYSTEM_ACCOUNTS_BY_COMPANY_NO_ACTION,
  GET_SYSTEM_COMPANY_ACCOUNTS_BY_COMPANY_NO_ACTION,
  CREATE_SYSTEM_ACCOUNTS_ACTION,
  DELETE_SYSTEM_ACCOUNTS_ACTION
};
