const LOGIN_API = 'login';
const REFRESH_API = 'refresh';
const CHANGE_PASSWORD_API = 'change_password';
const REQUEST_NEW_PASSWORD_API = 'users/request_new_password';
const RESET_PASSWORD_API = 'users/reset_password';

const LOGIN_ACTION = 'AUTH/LOGIN_ACTION';
const REFRESH_TOKEN_ACTION = 'AUTH/REFRESH_TOKEN_ACTION';
const CHANGE_PASSWORD_ACTION = 'AUTH/CHANGE_PASSWORD_ACTION';
const REQUEST_NEW_PASSWORD_ACTION = 'AUTH/REQUEST_NEW_PASSWORD_ACTION';
const RESET_PASSWORD_ACTION = 'AUTH/RESET_PASSWORD_ACTION';

export const typesApi = {
  LOGIN_API,
  REFRESH_API,
  CHANGE_PASSWORD_API,
  REQUEST_NEW_PASSWORD_API,
  RESET_PASSWORD_API
};

export const typesAction = {
  LOGIN_ACTION,
  REFRESH_TOKEN_ACTION,
  CHANGE_PASSWORD_ACTION,
  REQUEST_NEW_PASSWORD_ACTION,
  RESET_PASSWORD_ACTION
};
